spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQAKRrZHJBUqfeMIPZZDgGPXO6PX22VE5ZdmAiivlj9eBnE68ROUTbrONorsgNWpUJj3sD8uSS4cvoKyvT2X0cAkF+/TANX9UeoVJ6mrPmdr3aNCpVpHYna6cF6NtpYehiZL9endLhcpZQS7Y1ooBM1oBBP542kYPB8RlBelucqdn9w6qAUg3cVeA3eEFFz5yW/Zh+6fB3CyVpxtpGB76ZKoFOF9qr9JiXwnVXof58yhirrQmUiFSpUsmTh3klTjHhsGtn7i6oi8rdScPJVBOoe6m/wk0E8BXigvTnz6hs/UqxnZwrlEWGKFZDEUA+kQ9iWZd2B40i6HPEcIfasiG3kZQTWiCCAdPMf1jlHc/GHVUKVSk4MNEUTwkYN3l51hIFo='
    # {}넣어줘야 암호화된 문자가 된다 안쓰면 그냥 문자열 비밀번호

token:
  expiration_time: 86400000
  secret: '{cipher}AQB0BN+LXYpgpPfNE65N3AH/sRjGf6sKeLYVDzCEez0wnD4s75OzXiF62bLKw426oZ39DVf32ysQvaU/MbssrBtVAWIe/vQhJi99Zba90t26cOb78IZZmwJ13Cp+M28hNQx82kI3ujzhQu2mBWsbfrHgO3eeHZrnqQZkctDmSTgT/0/dWukIefrsxnGD8UvdJSXjGH2gskN15SZyYTRU/Cu4jpXm+o+Cdmn8b7iOMbgh/mED2C2WBNre96WFajNn2V+1vB77OER2z3YVrX05y0nr9ENhOQC6bTosSC295f1eX5+vtgyWa7v9pOeuQ9xc+ZojfTmDnjZKPeKJ6wqT9osXdyZEh969R8Yt5yAcyIf1ipjw9AzhZRoXcvHOf+g3l4n5mAAUwmXWRMW0xHeTkOVbuQxmKc2pknTqtQBD3SaXHg=='

gateway:
  ip: 192.168.55.162


order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: User's order is empty.